[package]
name = "pcg_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.1"
bevy_flycam = "*"
image = "0.25.1"

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
